syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "rangiffler-geo.proto";

package guru.qa.grpc.rangiffler;

option java_multiple_files = true;
option java_package = "guru.qa.rangiffler.grpc";
option java_outer_classname = "RangifflerPhotoProto";

service RangifflerPhotoService {
  rpc UpdatePhoto (PhotoRequest) returns(PhotoResponse);
  rpc CreatePhoto (PhotoRequest) returns(PhotoResponse);
  rpc ListPhoto (FeedRequest) returns(PhotoPageResponse);
  rpc Stat (StatRequest) returns(StatResponse);
  rpc PhotoLike (LikeRequest) returns(PhotoResponse);
  rpc DeletePhoto (PhotoDeleteRequest) returns(PhotoDeleteResponse);
}

message StatRequest {
  bool withFriends = 1;
  string userId = 2;
  string username = 5;
}

message StatResponse {
  repeated CountryStat stat = 1;
}

message CountryStat {
  uint32 count = 1;
  CountryValues country = 2;
}

message FeedRequest {
  bool withFriends = 1;
  string userId = 2;
  uint32 page = 3;
  uint32 size = 4;
  string username = 5;
}

message PhotoPageResponse {
  uint64 totalElements = 1;
  uint64 totalPages = 2;
  bool first = 3;
  bool last = 4;
  uint32 size = 5;
  repeated PhotoResponse edges = 6;
}

message PhotoRequest {
  string id = 1;
  string src = 2;
  CountryRequest country = 3;
  string description = 4;
  string userId = 5;
}

message LikeRequest {
  string userId = 1;
  string username = 2;
  string photoId = 3;
  string requesterId = 4;
}

message PhotoResponse {
  string id = 1;
  string src = 2;
  string firstname = 3;
  string description = 4;
  google.protobuf.Timestamp creationDate = 5;
  CountryValues country = 6;
  string userId = 7;
  repeated Like like = 8;
  bool isOwner = 9;
}

message Like {
  string userId = 1;
}

message PhotoDeleteRequest{
  string id = 1;
  string userId = 2;
}

message PhotoDeleteResponse {
  bool isDeleted = 1;
}