syntax = "proto3";

import "google/protobuf/empty.proto";
import "rangiffler-geo.proto";

package guru.qa.grpc.rangiffler;

option java_multiple_files = true;
option java_package = "guru.qa.rangiffler.grpc";
option java_outer_classname = "RangifflerUserdataProto";

service RangifflerUserdataService {
  // current user
  rpc CurrentUser (CurrentUserRequest) returns(UserResponse);
  rpc UpdateUser (UserRequest) returns(UserResponse);
  // All users
  rpc ListUsers (UserPageRequest) returns(UserPageResponse);
  // CRUD friend
  rpc ListFriends (UserPageRequest) returns(UserPageResponse);
  rpc SendRequest (FriendshipRequest) returns (UserResponse);
  rpc AcceptRequest (FriendshipRequest) returns (UserResponse);
  rpc DeclineRequest (FriendshipRequest) returns (UserResponse);
  rpc RemoveFriend (FriendshipRequest) returns (UserResponse);
  rpc ListOutcomeInvitations (UserPageRequest) returns(UserPageResponse);
  rpc ListIncomeInvitations (UserPageRequest) returns(UserPageResponse);
}

message FriendshipRequest {
  string requester = 1;
  string addressee = 2;
}

message UserRequest {
  string username = 2;
  string firstname = 3;
  string surname = 4;
  string avatar = 5;
  string country = 6;
}

message CurrentUserRequest {
  string username = 1;
}

message UserResponse {
  string id = 1;
  string username = 2;
  string firstname = 3;
  string surname = 4;
  string avatar = 5;
  CountryValues country = 6;
  FriendshipStatus friendshipStatus = 7;
}

message UserPageRequest {
  string username = 1;
  uint32 page = 2;
  uint32 size = 3;
  string searchQuery = 4;
}

message UserPageResponse {
  uint64 totalElements = 1;
  uint64 totalPages = 2;
  bool first = 3;
  bool last = 4;
  uint32 size = 5;
  repeated UserResponse edges = 6;
}

enum FriendshipStatus {
  NOT_FRIEND = 0;
  INVITATION_SENT = 1;
  INVITATION_RECEIVED = 2;
  FRIEND = 3;
}