syntax = "proto3";

import "google/protobuf/empty.proto";
import "rangiffler-geo.proto";

package guru.qa.grpc.rangiffler;

option java_multiple_files = true;
option java_package = "guru.qa.rangiffler.grpc";
option java_outer_classname = "RangifflerUserdataProto";

service RangifflerUserdataService {
  rpc CurrentUser (CurrentUserRequest) returns(UserResponse);
  rpc UpdateUser (UserRequest) returns(UserResponse);
  rpc ListUsers (UserPageRequest) returns(UserPageResponse);
}

message UserRequest {
  string username = 2;
  string firstname = 3;
  string surname = 4;
  string avatar = 5;
  string country = 6;
}

message CurrentUserRequest {
  string username = 1;
}

message UserResponse {
  string id = 1;
  string username = 2;
  string firstname = 3;
  string surname = 4;
  string avatar = 5;
  CountryValues country = 6;
  FriendshipStatus friendshipStatus = 7;
}

message UserPageRequest {
  string username = 1;
  uint32 page = 2;
  uint32 size = 3;
  string searchQuery = 4;
}

message UserPageResponse {
  uint64 totalElements = 1;
  uint64 totalPages = 2;
  bool first = 3;
  bool last = 4;
  uint32 size = 5;
  repeated UserResponse edges = 6;
}

enum FriendshipStatus {
  UNSPECIFIED_STATUS = 0;
  INVITE_SENT = 1;
  INVITE_RECEIVED = 2;
  FRIEND = 3;
}