syntax = "proto3";

import "google/protobuf/empty.proto";

package guru.qa.grpc.rangiffler;

option java_multiple_files = true;
option java_package = "guru.qa.rangiffler.grpc";
option java_outer_classname = "RangifflerGeoProto";

service RangifflerGeoService {
  rpc GetCountries (google.protobuf.Empty) returns (CountryPageResponse) {}
  rpc GetCountry (CountryRequest) returns (CountryResponse);
}

message CountryRequest {
  string code = 1;
}

message CountryPageResponse {
  repeated CountryResponse allCountries = 1;
}

message CountryResponse {
  string id = 1;
  string code = 2;
  string name = 3;
  string flag = 4;
}

enum CountryValues {
  COUNTRY_UNSPECIFIED = 0;
  TG = 1;
  LA = 2;
  MR = 3;
  NI = 4;
  LV = 5;
  OM = 6;
  AF = 7;
  CY = 8;
  BJ = 9;
  AQ = 10;
  CN = 11;
  CO = 12;
  CX = 13;
  AG = 14;
  MS = 15;
  MD = 16;
  ZM = 17;
  VN = 18;
  TF = 19;
  TD = 20;
  YT = 21;
  LB = 22;
  LU = 23;
  MQ = 24;
  CZ = 25;
  AE = 26;
  CM = 27;
  BI = 28;
  AR = 29;
  AS = 30;
  BH = 31;
  CL = 32;
  AD = 33;
  MP = 34;
  LT = 35;
  MG = 36;
  LC = 37;
  TR = 38;
  UA = 39;
  TV = 40;
  VI = 41;
  MT = 42;
  NO = 43;
  MC = 44;
  CH = 45;
  AW = 46;
  BZ = 47;
  BM = 48;
  CI = 49;
  MU = 50;
  US = 51;
  TW = 52;
  YE = 53;
  MW = 54;
  NL = 55;
  LS = 56;
  BO = 57;
  AT = 58;
  CK = 59;
  BY = 60;
  AU = 61;
  BN = 62;
  MA = 63;
  NZ = 64;
  LR = 65;
  MV = 66;
  TC = 67;
  UG = 68;
  TT = 69;
  PL = 70;
  IN = 71;
  GE = 72;
  GR = 73;
  GS = 74;
  GD = 75;
  IO = 76;
  HK = 77;
  KP = 78;
  KG = 79;
  PM = 80;
  SV = 81;
  RE = 82;
  SA = 83;
  SC = 84;
  ST = 85;
  KE = 86;
  KR = 87;
  GF = 88;
  DJ = 89;
  GQ = 90;
  GP = 91;
  DK = 92;
  IL = 93;
  PN = 94;
  SB = 95;
  PY = 96;
  RU = 97;
  KW = 98;
  DO = 99;
  GT = 100;
  GB = 101;
  GU = 102;
  HM = 103;
  SG = 104;
  PK = 105;
  SR = 106;
  SE = 107;
  JP = 108;
  GW = 109;
  EH = 110;
  DZ = 111;
  GA = 112;
  FR = 113;
  DM = 114;
  HN = 115;
  SD = 116;
  RW = 117;
  PH = 118;
  QA = 119;
  PE = 120;
  PR = 121;
  SI = 122;
  HT = 123;
  ES = 124;
  GL = 125;
  GM = 126;
  ER = 127;
  FI = 128;
  EE = 129;
  KN = 130;
  HU = 131;
  IQ = 132;
  KY = 133;
  SH = 134;
  PS = 135;
  PF = 136;
  SJ = 137;
  ID = 138;
  IS = 139;
  EG = 140;
  FK = 141;
  FJ = 142;
  GN = 143;
  GY = 144;
  IR = 145;
  KM = 146;
  IE = 147;
  KZ = 148;
  RO = 149;
  SK = 150;
  PG = 151;
  PT = 152;
  SO = 153;
  HR = 154;
  KI = 155;
  JM = 156;
  EC = 157;
  ET = 158;
  FO = 159;
  KH = 160;
  SY = 161;
  SN = 162;
  PW = 163;
  SL = 164;
  FM = 165;
  GI = 166;
  DE = 167;
  GH = 168;
  JO = 169;
  IT = 170;
  PA = 171;
  SZ = 172;
  SM = 173;
  TN = 174;
  ML = 175;
  CG = 176;
  AO = 177;
  BT = 178;
  AN = 179;
  BB = 180;
  CF = 181;
  MM = 182;
  LI = 183;
  NA = 184;
  MZ = 185;
  TO = 186;
  VG = 187;
  VE = 188;
  TZ = 189;
  TM = 190;
  MX = 191;
  NC = 192;
  MO = 193;
  LK = 194;
  CD = 195;
  AL = 196;
  BW = 197;
  CR = 198;
  BV = 199;
  AM = 200;
  AZ = 201;
  BA = 202;
  MN = 203;
  NU = 204;
  MY = 205;
  TL = 206;
  WS = 207;
  TH = 208;
  NF = 209;
  LY = 210;
  AI = 211;
  BR = 212;
  CV = 213;
  BE = 214;
  CA = 215;
  BD = 216;
  BS = 217;
  NG = 218;
  MK = 219;
  NP = 220;
  VA = 221;
  UZ = 222;
  UM = 223;
  TK = 224;
  VC = 225;
  ZW = 226;
  NR = 227;
  NE = 228;
  CU = 229;
  BF = 230;
  BG = 231;
  CC = 232;
  MH = 233;
  ZA = 234;
  UY = 235;
  WF = 236;
  VU = 237;
  TJ = 238;
}