rootProject.name = 'rangiffler'

def modules = [
        'rangiffler-gateway',
        'rangiffler-auth',
        'rangiffler-userdata',
        'rangiffler-photo',
        'rangiffler-geo',
        'rangiffler-grpc-common',
        'rangiffler-e-2-e-tests'
]

modules.each { m ->
    if (file(m).exists()) {
        include m
    }
}