plugins {
    id 'org.springframework.boot' version '3.5.5'
    id 'com.google.cloud.tools.jib' version '3.4.1'
}

group = 'guru.qa'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':rangiffler-grpc-common')
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation("net.devh:grpc-server-spring-boot-starter:${project.ext.springGrpcVersion}") {
        exclude group: 'io.grpc'
        exclude group: 'com.google.protobuf'
    }
    implementation("net.devh:grpc-client-spring-boot-starter:${project.ext.springGrpcVersion}") {
        exclude group: 'io.grpc'
        exclude group: 'com.google.protobuf'
    }
    implementation "com.google.protobuf:protobuf-java-util:${project.ext.protobufVersion}"
    implementation "io.grpc:grpc-netty-shaded:${project.ext.grpcVersion}"
    implementation "io.grpc:grpc-services:${project.ext.grpcVersion}"
    implementation "io.grpc:grpc-inprocess:${project.ext.grpcVersion}"
    implementation "org.flywaydb:flyway-core:${project.ext.flywayVersion}"
    implementation "org.flywaydb:flyway-mysql:${project.ext.flywayVersion}"
    runtimeOnly "mysql:mysql-connector-java:${project.ext.mysqlDriverVersion}"
    annotationProcessor "org.projectlombok:lombok:${project.ext.lombokVersion}"
    compileOnly "org.projectlombok:lombok:${project.ext.lombokVersion}"
}

jib {
    container {
        ports = ['8093', '8094']
        jvmFlags = ["-Dspring.profiles.active=${System.env.PROFILE}"]
        environment = [
                'VAULT_TOKEN': "${System.env.VAULT_TOKEN}".toString(),
                'TZ'         : 'Europe/Moscow'
        ]
        creationTime = 'USE_CURRENT_TIMESTAMP'
        labels = [
                'maintainer': 'Amurskii Andrey @E_eq_mc2',
                'version'   : "${project.version}".toString()
        ]
    }
    from {
        image = "${project.ext.dockerImage}"
        platforms {
            platform {
                architecture = "${project.ext.dockerArch}"
                os = 'linux'
            }
        }
    }
    to {
        image = "${project.ext.dockerHubName}/${project.name}-${System.env.PROFILE}"
        tags = ['latest', "${project.version}"]
    }
}

tasks.jibDockerBuild.dependsOn test

tasks.register('printVersion') {
    doLast {
        println project.version
    }
}