plugins {
    id 'org.springframework.boot' version '3.5.8'
    id 'com.netflix.dgs.codegen' version '8.3.0'
    id 'com.google.cloud.tools.jib' version '3.4.1'
}

group = 'guru.qa'
version = '1.0.0'

generateJava {
    typeMapping = [
            "UserConnection": "graphql.relay.DefaultConnection<User>",
            "PhotoConnection": "graphql.relay.DefaultConnection<Photo>"
    ]
    schemaPaths = ["${projectDir}/src/main/resources/graphql"]
    subPackageNameClient = 'graphqlClient'
    subPackageNameTypes = 'graphqlTypes'
    subPackageNameDatafetchers = 'graphqlDatafetchers'
    packageName = 'rangiffler'
    generateClientv2 = true
    javaGenerateAllConstructor = true
    trackInputFieldSet = true
}

// Создаем конфигурацию и исключаем зависимость
configurations {
    customPluginConfiguration {
        exclude group: 'com.netflix.dgs.codegen', module: 'jackson-bom'
    }
}

dependencies {
    implementation project(':rangiffler-grpc-common')
    compileOnly 'com.netflix.graphql.dgs:graphql-dgs-pagination:11.1.0'
    // spring
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation('org.springframework.boot:spring-boot-starter-web-services') {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
    }
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    // grpc
    implementation("net.devh:grpc-client-spring-boot-starter:${project.ext.springGrpcVersion}") {
        exclude group: 'io.grpc'
        exclude group: 'com.google.protobuf'
    }
    implementation "com.google.protobuf:protobuf-java-util:${project.ext.protobufVersion}"
    implementation "io.grpc:grpc-netty-shaded:${project.ext.grpcVersion}"
    implementation "io.grpc:grpc-services:${project.ext.grpcVersion}"
    implementation "io.grpc:grpc-inprocess:${project.ext.grpcVersion}"
    // gql
    implementation 'org.springframework.boot:spring-boot-starter-graphql'
    customPluginConfiguration 'com.netflix.dgs.codegen:com.netflix.dgs.codegen.gradle.plugin:4.3.1'
    implementation 'com.tailrocks.graphql:graphql-datetime-spring-boot-starter:6.0.0'
    // anno
    implementation 'com.google.code.findbugs:jsr305:3.0.2'
    annotationProcessor "org.projectlombok:lombok:${project.ext.lombokVersion}"
    compileOnly "org.projectlombok:lombok:${project.ext.lombokVersion}"
    // db
    implementation "org.flywaydb:flyway-core:${project.ext.flywayVersion}"
    implementation "org.flywaydb:flyway-mysql:${project.ext.flywayVersion}"
    runtimeOnly "mysql:mysql-connector-java:${project.ext.mysqlDriverVersion}"
}

jib {
    container {
        ports = ['8080']
        jvmFlags = ["-Dspring.profiles.active=${System.env.PROFILE}"]
        environment = [
                'VAULT_TOKEN': "${System.env.VAULT_TOKEN}".toString(),
                'TZ'         : 'Europe/Moscow'
        ]
        creationTime = 'USE_CURRENT_TIMESTAMP'
        labels = [
                'maintainer': 'Amurskii Andrey @E_eq_mc2',
                'version'   : "${project.version}".toString()
        ]
    }
    from {
        image = "${project.ext.dockerImage}"
        platforms {
            platform {
                architecture = "${project.ext.dockerArch}"
                os = 'linux'
            }
        }
    }
    to {
        image = "${project.ext.dockerHubName}/${project.name}-${System.env.PROFILE}"
        tags = ['latest', "${project.version}"]
    }
}

tasks.jibDockerBuild.dependsOn test

tasks.register('printVersion') {
    doLast {
        println project.version
    }
}
